#!/bin/bash

#SBATCH --export=ALL
#SBATCH --partition=standard
#SBATCH --account=account_name
#SBATCH --distribution=cyclic
#SBATCH --nodes=1
#SBATCH --ntasks=1
#SBATCH --cpus-per-task=20 # no benefit using more than 20 threads as HT is not useful for us
#SBATCH --time=00:20:00
#SBATCH --job-name=JitPIC
#SBATCH --output=slurm-%j.out

module purge
module load anaconda/python-3.8.8/2021.04 # should be the same version as JitPIC is installed under
export NUMBA_NUM_THREADS=$SLURM_CPUS_PER_TASK
export NUMBA_THREADING_LAYER=omp # OpenMP threading is slightly faster than TBB (the default)

#======================================================
# Prologue script to record job details
# Do not change the line below
#======================================================
/opt/software/scripts/job_prologue.sh  
#------------------------------------------------------

python simulation_script.py

#======================================================
# Epilogue script to record job endtime and runtime
# Do not change the line below
#======================================================
/opt/software/scripts/job_epilogue.sh 
#------------------------------------------------------